### ISSUE TITLE
关于提交报告的逻辑

### ISSUE THREAD

**Issue by Hamal-z** [cycoe/class_robber#1]
学长/学姐 你好，我尝试用这个项目来抢学术报告，但可能是由于教务网做了变动，现在在提交报告的部分会返回HTTP500错误。
我看了源代码的逻辑是首先访问报告详情页面，然后从详情页面跳转来提交报告申请。现在的教务系统抢报告是需要输入验证码的，我想问一下代码里做一次跳转是为了绕过验证码吗，如果不是的话，请问先访问报告详情页面再提交报告申请是出于什么考虑？

**Comment by cycoe** [comment]
学弟你好，这个项目已经有比较长的时候没有进行维护了，目前我也已经毕业没有办法进行调试。我印象中先进入详情页是为了绕过验证码，如果现在页面逻辑发生变化的话也可以直接从报告列表处进行提交，并附带上识别出的验证码。但由于识别精度问题此方法效率会比绕过验证码的方式要低，你可以进行尝试。

另外，如果你愿意接手这个项目的话我也很欢迎

**Comment by Hamal-z** [comment]
感谢你的回答，验证码部分我再尝试尝试👌
